AI ML 
ASSIGNMENT NO - 13 

name - shahid ahmad khan 
college - manav school of polytechnic 


question 1 - Write a program to 
a) Create a 1D array with elements [10, 20, 30, 40, 50] using np.array().
b) Create a 2D array (3x3) using np.array().
c) Print both arrays along with their shape and data type (dtype).


In [1]:
import numpy as np
# create a 1d array
array1 = np.array([10, 20, 30, 40, 50])
# create a 2d array (3 x 3) array
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print 1d array
print("Array 1:")
print(array1)
print("shape:",array1.shape)
print("data type:",array1.dtype)
print()
# print 2d array
print("Array 2:")
print(array2)
print("shape:",array2.shape)
print("data type:",array2.dtype)

Array 1:
[10 20 30 40 50]
shape: (5,)
data type: int64

Array 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
data type: int64


question 2 - Create the following using NumPy:
a) A 1D array of 8 zeros.
b) A 2D array of shape (4, 4) filled with ones.
c) A 3x3 matrix of zeros.
d) Print all arrays with proper labels.


In [2]:
import numpy as np

# 1D array of 8 zeroes
arr1 = np.zeros(8)

# 2D array of shape (4,4) filled with ones
arr2 = np.ones((4,4))

# 3X3 matrix of zeroes
arr3 = np.zeros((3,3))

# print all arrays with proper labels
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)

Array 1: [0. 0. 0. 0. 0. 0. 0. 0.]
Array 2: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array 3: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


question 3 - Use np.arange() to create and print the following arrays:
a) Numbers from 0 to 20 (step 1).
b) Even numbers from 10 to 50.
c) Numbers from 5 to 100 with step of 5.


In [3]:
import numpy as np

# a) number from 0 to 20 (step 1)

arr1 = np.arange(0, 21, 1)

# b) even number from 10 to 50

arr2 = np.arange(10, 51, 2)

# c) numbers from 5 to 100 with steps of 5

arr3 = np.arange(5, 101, 5)

# print all arrays

print("a) number from 0 to 20 (step 1):", arr1)

print(arr1)

print("b) even number from 10 to 50:", arr2)

print(arr2)

print("c) numbers from 5 to 100 with steps of 5:", arr3)

print(arr3)

a) number from 0 to 20 (step 1): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
b) even number from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
c) numbers from 5 to 100 with steps of 5: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


question 4 - Use np.linspace() to create:
a) 10 equally spaced numbers between 0 and 5.
b) 15 equally spaced numbers between -10 and 10.
c) Print the arrays and their length.


In [4]:
import numpy as np

# a) 10 equally spaced numbers between 0 and 5
array1 = np.linspace(0, 5, 10)

# b) 15 equally spaced numbers between -10 and 10
array2 = np.linspace(-10, 10, 15)

# c) print all the arrays and their length
print("a) 10 equally spaced numbers between 0 and 5:")
print(array1)
print("Length of array1:", len(array1))
print("b) 15 equally spaced numbers between -10 and 10:")
print(array2)
print("Length of array2:", len(array2))

a) 10 equally spaced numbers between 0 and 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length of array1: 10
b) 15 equally spaced numbers between -10 and 10:
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length of array2: 15


question 5 - Write a program to generate:
a) A 1D array of 10 random numbers between 0 and 1 using np.random.rand().
b) A 3x3 matrix of random numbers from standard normal distribution using np.random.randn().
c) A 2D array (4x5) of random integers between 10 and 50 using np.random.randint().
d) Print all with proper headings.

In [5]:

import numpy as np

# a) 1D array of 10 random numbers between 0 and 1
array1 = np.random.rand(10)

# b) 3x3 matrix of random numbers from standard normal distribution
array2 = np.random.randn(3, 3)

# c) 4x5 array of random integers between 10 and 50
array3 = np.random.randint(10, 51, (4, 5))

# Print all arrays
print("a) 1D Array of 10 Random Numbers (0 to 1):")
print(array1)
print("b) 3x3 Matrix of Random Numbers (Standard Normal Distribution):")
print(array2)
print("c) 4x5 Array of Random Integers (10 to 50):")
print(array3)

a) 1D Array of 10 Random Numbers (0 to 1):
[0.13370922 0.43654715 0.88569976 0.66178274 0.02990169 0.30780424
 0.00354496 0.70013017 0.67169588 0.26908748]
b) 3x3 Matrix of Random Numbers (Standard Normal Distribution):
[[ 0.12586121  1.38097678 -1.28340656]
 [-1.18080493  0.23188227  0.09950964]
 [-0.40951786  0.54168686  0.2485398 ]]
c) 4x5 Array of Random Integers (10 to 50):
[[31 15 41 25 14]
 [21 33 33 33 23]
 [47 36 19 17 32]
 [26 50 49 16 19]]


question 6 - Create two vectors:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
Perform and print:
Addition
Subtraction
Element-wise multiplication
Dot product


In [6]:
# create vectors
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

# addition
print("Addition:", v1 + v2)

# subtraction
print("Subtraction:", v1 - v2)

# element-wise multiplication
print("Element-wise Multiplication:", v1 * v2)

# dot product
print("Dot Product:", np.dot(v1, v2))

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56]
Dot Product: 100


question 7 - Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform the following:
Matrix addition
Matrix multiplication (@ or np.dot())
Element-wise multiplication (*)
Print the results clearly.


In [7]:

import numpy as np

# create matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# matrix addition
print("Matrix Addition:")
print(A + B)

# matrix multiplication
print("Matrix Multiplication (using @ operator):")
print(A @ B)

# element-wise multiplication
print("Element-wise Multiplication:")
print(A * B)



Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Multiplication (using @ operator):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


question 8 - Create a 4x4 matrix of random integers between 1 and 100.
Print:
Shape
Dimension (ndim)
Total number of elements (size)
Data type
minimum and maximum values 

In [8]:
import numpy as np

# Create a 4x4 matrix of random integers between 1 and 100
matrix = np.random.randint(1, 101, (4, 4))

# print the matrix
print("Matrix:")
print(matrix)

# print matrix properties
print("Shape of the matrix:", matrix.shape)
print("Dimension of the matrix:", matrix.ndim)
print("Total number of elements in the matrix:",matrix.size)
print("Data type of the matrix:", matrix.dtype)
print("Minimum value in the matrix:", np.min(matrix))
print("Maximum value in the matrix:", np.max(matrix))

Matrix:
[[85 24 96 51]
 [ 6 30 56 22]
 [81 11 81  5]
 [62 10 21 77]]
Shape of the matrix: (4, 4)
Dimension of the matrix: 2
Total number of elements in the matrix: 16
Data type of the matrix: int32
Minimum value in the matrix: 5
Maximum value in the matrix: 96


question 9 - Generate a 1D array of 20 random integers between 1 and 50 using
np.random.randint().
Reshape it into a 4x5 matrix.
Print the sum, mean, and standard deviation of the matrix.
Find the maximum value in each row.


In [9]:
import numpy as np

# Generate a 1D array of 20 random integers between 1 and 50
arr = np.random.randint(1, 51, size=20)

# reshape it into a 4x5 matrix
matrix = arr.reshape(4, 5)

# print the matrix
print("4x5 matrix")
print(matrix)

# print the sum , mean and standard deviation of the matrix
print("Sum of the matrix: ", np.sum(matrix))
print("Mean of the matrix: ", np.mean(matrix))
print("Standard Deviation of the matrix: ", np.std(matrix))

# find the maximum value in each row
print("Maximum values in each row: ")
print(matrix.max(axis=1))

4x5 matrix
[[34 49 44 26 14]
 [34  6 39 45 30]
 [10  2 13 21 19]
 [40 20 49 26 25]]
Sum of the matrix:  546
Mean of the matrix:  27.3
Standard Deviation of the matrix:  13.917973990491575
Maximum values in each row: 
[49 45 21 49]


question 10 ) Create a Simple Statistics Calculator using NumPy


In [ ]:
import numpy as np

try:
    # Ask the user for the number of elements
    n = int(input("Enter how many numbers you want to generate: "))

    if n <= 0:
        print("Please enter a positive number.")
    else:
        # Generate random numbers between 10 and 100
        array = np.random.randint(10, 101, size=n)

        # Print the array
        print("Generated Array:")
        print(array)

        # Print statistics
        print("Mean:", np.mean(array))
        print("Median:", np.median(array))
        print("Standard Deviation:", np.std(array))
        print("Minimum Value:", np.min(array))
        print("Maximum Value:", np.max(array))

        # Reshape into a 2D array if possible
        rows = int(np.sqrt(n))

        if rows > 1 and n % rows == 0:
            matrix = array.reshape(rows, n // rows)

            print("Reshaped 2D Array:")
            print(matrix)

            print("Row-wise Sum:")
            print(np.sum(matrix, axis=1))
        else:
            print("Cannot reshape into a 2D array.")

except ValueError:
    print("Invalid input! Please enter an integer number.")